apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: __NAME__
  namespace: websites
  annotations:
    kubernetes.io/ingress.class: "public"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/from-to-www-redirect: "true"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "md5"
    ingress.kubernetes.io/auth-secret: basic-auth
    ingress.kubernetes.io/auth-realm: "Authentication Required!"
    __AUTH__
spec:
  tls:
  - secretName: lets-encrypt
    hosts:
